### ISSUE TITLE
Kein PDF

### ISSUE THREAD

**Issue by DO1JLR** [maxbachmann-snips/presentation-snips#3]
Anderes Thema: Heute Toolbox?
@Devil0000 ist auch da! Und evtl @drwuro?

**Comment by drwuro** [comment]
wot is dis?

bzgl toolbox: bin leider erst morgen wieder am start

**Comment by DO1JLR** [comment]
> wot is dis?
> 
> bzgl toolbox: bin leider erst morgen wieder am start

Ein random github weil max nicht per chat antwortet...

Schade, bis morgen

**Comment by drwuro** [comment]
mir ist in der lounge uebrigens ein cooler platz aufgefallen wo man ein technikcamp-poster aufhaengen koennte

**Comment by DO1JLR** [comment]
Klingt interessant! Ich hoffe ich kann die bald vorbei bringen.

**Comment by DEvil0000** [comment]
asdf

**Comment by DO1JLR** [comment]
Hey @devil0000 , ich hab hunger.

Abendessen?

**Comment by DEvil0000** [comment]
dito, mach mal

**Comment by DO1JLR** [comment]
nach dir

**Comment by DO1JLR** [comment]
Oder @drwuro bestellt uns wieder Pizza!

**Comment by drwuro** [comment]
weiss nicht ob ich das von remote aus so gut hinbekomme!

**Comment by maxbachmann** [comment]
Keine Chat Plattform ... 
btw pdf gibts hier schon: https://github.com/maxbachmann-snips/presentation-snips/releases

**Comment by maxbachmann** [comment]
@DO1JLR vielleicht ja doch eine chat Plattform

**Comment by DO1JLR** [comment]
jep

**Comment by DO1JLR** [comment]
https://revealjs.com/#/ @maxbachmann
